services:
  db:
    image: postgres:17
    container_name: cyberman-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env_db
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "max_wal_size=2GB"]

  web:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: cyberman-web
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "9000:9000"
    #command: ["gunicorn", "dashboard.wsgi:application", "--bind", "0.0.0.0:9000"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:9000"]

volumes:
  postgres_data:
  static_volume: